let num = 2;
let num2 = 10;
let soma = num + num2;
let sub = num - num2;
let mult = num * num2;
let div = num / num2;
console.log(`O resultado da soma entre 2 e 10 é ${soma}`);
console.log(`O resultado da subtração entre 2 e 10 é ${sub}`);
console.log(`O resultado da multiplicação entre 2 e 10 é ${mult}`);
console.log(`O resultado da divisão entre 2 e 10 é ${div}`);
